:concurrency: 25
:logfile: ./log/sidekiq.log

production:
  :concurrency: 4

:schedule:
  daily_import:
    cron: '0 0 * * *' # Runs once a day at 00:00
    class: HomebrewFormulaImportWorker
  monthly_formula_yearly_hits_update:
    cron: '0 0 1 * *' # Runs the first day of each month at 00:00
    class: FormulaYearHitsUpdateWorker
